<div class="footer">
	<h2>
		Embracing Serendipity: From Biochemistry to Data Visualization — Two Unique
		Journeys Unite
	</h2>
	<h3>by Alenka Guček and Matthias Stahl</h3>
	<h5>info+, Edinburgh, 24th November 2023</h5>
	<div class="image-credits">
		<p>
			The code of this website can be found <a
				href="https://github.com/higsch/community-universe">here</a
			>.
		</p>
		<p>Illustrations are AI-generated by Midjourney.</p>
		<p>
			The DVS badge legend is taken from <a
				href="https://www.datavisualizationsociety.org/dvs-badge">here</a
			>. Thanks to
			<a href="https://observablehq.com/@osserman">Stephen Osserman</a> who coded
			the SVG badge generator.
		</p>
		<p>
			Other image credits: <a
				href="https://en.wikipedia.org/wiki/Flag_of_Sweden#/media/File:Flag_of_Sweden.svg"
				>Sweden flag</a
			>, <a href="https://no.linkedin.com/in/aamorelli">Angela Morelli</a>,
			<a href="https://twitter.com/SonjaKuijpers">Sonja Kuijpers</a>,
			<a href="https://www.meetup.com/de-DE/data-visualization-bremen/"
				>Moritz Stefaner</a
			>,
			<a href="https://www.gabrielaplucinska.com/about">Gabriela Plucinska</a>,
			<a href="https://datajournalism.com/contributors/maartenzam"
				>Maarten Lambrechts</a
			>,
			<a href="https://www.inbal-rief.com/about">Inbal Rief</a>,
			<a href="https://www.visualcinnamon.com/about/">Nadieh Bremer</a>,
			<a href="https://www.nawik.de/team/helena-jambor/">Helena Jambor</a>,
			<a
				href="https://www.maartenlambrechts.com/2021/07/02/visualizing-a-genome-collection-with-cactustrees.html"
				>Genome collection by Maarten Lambrechts</a
			>
		</p>
	</div>
</div>

<style>
	.footer {
		display: flex;
		flex-direction: column;
		justify-content: center;
		align-items: center;
		width: 100%;
		height: 100vh;
		padding: 1rem;
	}

	h2,
	h3,
	h5 {
		text-align: center;
	}

	.image-credits {
		margin-top: 3rem;
		text-align: center;
	}

	.image-credits p {
		font-size: 0.8rem;
		color: var(--code-color);
	}
</style>
