<div class="footer">
	<h3>Alenka Guček and Matthias Stahl</h3>
	<h2>
		Embracing Serendipity: From Biochemistry to Data Visualization — Two Unique
		Journeys Unite
	</h2>
	<p class="abstract">
		In the dynamic world of data visualization, diverse paths often converge to
		create captivating narratives. Alenka and Matthias, once biochemists turned
		data visualization professionals, share their transformative journeys.
		Making the switch to dataviz from being academic fellows in Sweden, they
		talk about their paths when their passions for visualization ignited.
		Alenka's fascination with molecular intricacies pushed her beyond
		traditional charts, merging her love for molecular structures with artistic
		visualization. Matthias, on the other hand, found his passion during his
		postdoc tenure in Stockholm, using data art to communicate complex
		information effectively. Their stories reveal shared enthusiasm for
		impactful visualizations, bridging scientific exploration and community
		engagement. Regardless of their academic origins, their journeys underscore
		the power of pursuing true passions. In this presentation, we explore Alenka
		and Matthias' parallel experiences, celebrating diverse paths into data
		visualization. We invite the community to reflect on their unique journeys
		for shared understanding and discovery.
	</p>
	<div class="image-credits">
		<p>
			The code of this website can be found <a
				href="https://github.com/higsch/community-universe">here</a
			>.
		</p>
		<p>Illustrations are AI-generated by Midjourney.</p>
		<p>
			The DVS badge legend is taken from <a
				href="https://www.datavisualizationsociety.org/dvs-badge">here</a
			>. Thanks to
			<a href="https://observablehq.com/@osserman">Stephen Osserman</a> who coded
			the SVG badge generator.
		</p>
		<p>
			Other image credits: <a
				href="https://en.wikipedia.org/wiki/Flag_of_Sweden#/media/File:Flag_of_Sweden.svg"
				>Sweden flag</a
			>, <a href="https://no.linkedin.com/in/aamorelli">Angela Morelli</a>,
			<a href="https://twitter.com/SonjaKuijpers">Sonja Kuijpers</a>,
			<a href="https://www.meetup.com/de-DE/data-visualization-bremen/"
				>Moritz Stefaner</a
			>,
			<a href="https://www.gabrielaplucinska.com/about">Gabriela Plucinska</a>,
			<a href="https://datajournalism.com/contributors/maartenzam"
				>Maarten Lambrechts</a
			>,
			<a href="https://www.inbal-rief.com/about">Inbal Rief</a>,
			<a href="https://www.visualcinnamon.com/about/">Nadieh Bremer</a>,
			<a href="https://www.nawik.de/team/helena-jambor/">Helena Jambor</a>,
			<a
				href="https://www.maartenlambrechts.com/2021/07/02/visualizing-a-genome-collection-with-cactustrees.html"
				>Genome collection by Maarten Lambrechts</a
			>
		</p>
	</div>
</div>

<style>
	.footer {
		display: flex;
		flex-direction: column;
		justify-content: center;
		align-items: center;
		width: 100%;
		padding: 2rem 1rem 1rem 1rem;
	}

	h2,
	h3 {
		text-align: center;
	}

	h2 {
		font-family: Handlee;
	}

	h3 {
		font-size: 0.9rem;
		font-weight: normal;
	}

	p.abstract {
		padding: 0 1rem;
		max-width: 900px;
		font-size: 0.9rem;
		line-height: 1.8;
	}

	.image-credits {
		margin-top: 3rem;
		text-align: center;
	}

	.image-credits p {
		font-size: 0.8rem;
		color: var(--code-color);
	}
</style>
